version: "3.8"

services:
  db:
    platform: linux/arm64
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_USERNAME: $MYSQLDB_USERNAME
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      - db
    restart: on-failure
    image: bookshop-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://localhost:3306/bookstore:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
            "spring.datasource.username" : "MYSQLDB_USER",
            "spring.datasource.password" : "MYSQLDB_PASSWORD"
          }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
